### PR TITLE
3d banner

### PR DESCRIPTION
**Pull request by lividhen**
I really like the 3d banners, so I made a couple. 

This is NOT ready to merge, there are 2 banner files there, because I couldn't decide which one to suggest 😅. There don't seem to be any community tools that can handle the animation of, otherwise I would have done so...

I will upload images of them asap

Edit: Here is banner.cgfx:

I am not at my computer to build banner two atm, but now that I have stepped back I realize they are quite small. I will scale them up, and probably change some proportions just a little. 

Thanks to PabloMK7, he gave me a lot of help. And thanks to nickthegamer5 for the guide. [here](https://gbatemp.net/threads/tutorial-creating-3d-banners-from-3d-models-for-cias.433783/)

### CODE REVIEW

**Comment by SuperSaiyajinStackZ** [comment]
The 3D Banner may look nice and great.. but at the other side, it would look like it uses SDK Tools which is illegal in topics Homebrew.

**Comment by Epicpkmn11** [comment]
Plenty<sup>[[1]](https://github.com/Nanquitas/BootNTR)[[2]](https://github.com/RSDuck/craftus_reloaded)[[3]](https://github.com/Steveice10/FBI)[[4]](https://github.com/mariohackandglitch/homebrew_launcher_dummy)[[5]](https://github.com/TuxSH/TWLSaveTool)</sup> or other homebrew apps use 3D banners and a quick search finds [a tutorial](https://gbatemp.net/threads/tutorial-creating-3d-banners-from-3d-models-for-cias.433783/), so it I think it's nice ;P

**Comment by Epicpkmn11** [comment]
Also that's `banner.cgfx`, banner2.cgfx` is this for anyone else who's curious:

banner2.cgfx

**Comment by lividhen** [comment]
> Also that's `banner.cgfx`, `banner2.cgfx` is this for anyone else who's curious:
> 
> banner2.cgfx
> 
> imo having the title is nice, as the 3DS doesn't show it anywhere else unless you're all the way zoomed in and not in a folder, though I think it would be nice to make it not mirrored on the back side if possible. Maybe a triangle or square with the text on all sides could be nice? Then it should always be fairly readable. Or maybe just make it transparent around the letters and then it shouldn't look as odd when mirrored.
> 
> I also think all the little arrows is kinda neat... Not sure which I prefer either tbh lol
> 
> 

OH! Darn it! The alpha channel got messed up! 😂 Normally the black around the letters is transparency. 

I like your idea of the shape with the text on all sides. What I wanted to do originally is enable back face culling on the material with the letters, and have one mirrored behind it, so that the text would be facing the correct direction 100% of the time, but I can't figure out how to do it.

I guess this is sort of "spit balling" so I am not against changing the models, or creating new ones! I could put the text into the multi-arrow one, and see how that looks.

**Comment by lividhen** [comment]
> Plenty<sup>[[1]](https://github.com/Nanquitas/BootNTR)[[2]](https://github.com/RSDuck/craftus_reloaded)[[3]](https://github.com/Steveice10/FBI)[[4]](https://github.com/mariohackandglitch/homebrew_launcher_dummy)[[5]](https://github.com/TuxSH/TWLSaveTool)</sup> of other homebrew apps use 3D banners and a quick search finds [a tutorial](https://gbatemp.net/threads/tutorial-creating-3d-banners-from-3d-models-for-cias.433783/) that doesn't use SDK tools, so it I think it's nice ;P
> 
> 

Yep! That is the exact tutorial I referenced when creating them! I used blender instead of wings 3d, A because I already know blender and B because I could not figure out how to use wings 3d for the life of me 😂.

**Comment by lividhen** [comment]
image
Ok! Here is with the multiple arrows and text, i am using vvctre because i don't have my 3ds with me, i hope it doesn't look any different on there than on a real 3ds.

**Comment by Epicpkmn11** [comment]
> If nobody knows how to fix the transparency, what shape or object do you guys want the "Universal Updater" text to be put on? I don't know what to do for the background of that object either... Just solid black feels weird and unfinished 😆. I suppose I could also create modeled text, but that tends to take a LOT of vertices... I have found that anything too high poly will crash and or lag.

Oh I didn't see this edit, as I said above I think probably either square or triangle with the text on all sides might work well.

Maybe a square would work best as it can match the arrow.

**Comment by lividhen** [comment]
Sorry for all the commit spam. I am really bad at making sure things work, and just using git 😅.
##
Here is one of them, i like this one better. The text is on a plane. It was hard to see on a cube without it being huge. The background of the text looks odd, that might need to be changed, but here is the idea.
image
##
I also had the idea of just sticking it to the sides, but its quite hard to see.
image

**Comment by Epicpkmn11** [comment]
Oh, what's the status of this? Looks like I never replied 😅 

I think either of the last couple look good imo, so if this is ready to merge we're planning a new release within a couple days so should probably merge this, if not how close is it to being good?

**Comment by lividhen** [comment]
OK, let me know if anything is wrong.

**Comment by Epicpkmn11** [comment]
Looks good to me

**Pull request merged**
